server:
  port: 8080

spring:
  application:
    name: spring-app
  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
