spring:
  cloud:
    consul:
      enabled: true
      discovery:
        enabled: true
        instanceId: "${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}"
        prefer-ip-address: false
        health-check-critical-timeout: "1m"

logging:
  config:
   classpath:logback-consul.xml
