version: "3.8"

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}

services:

  postgresql:
    image: postgres:13.4
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=
      - TZ=Asia/Seoul
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - monitoring

  consul-server:
    image: hashicorp/consul:1.10.3
    container_name: consul-server
    restart: always
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
    networks:
      - monitoring
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "consul agent -dev -ui -client 0.0.0.0 -log-level=INFO"

  spring-hello:
    build:
      context: spring-hello
      dockerfile: Dockerfile
    container_name: hello
    image: ilovecorea/spring-hello:${TAG:-latest}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=consul
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul-server
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - "8080:8080"
    networks:
      - monitoring
    depends_on:
      - consul-server

  spring-blog:
    build:
      context: spring-blog
      dockerfile: Dockerfile
    container_name: blog
    image: ilovecorea/spring-blog:${TAG:-latest}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=consul
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul-server
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - "8081:8080"
    networks:
      - monitoring
    depends_on:
      - consul-server

  node-exporter:
    image: prom/node-exporter:v1.2.2
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitoring

#  prometheus-bot:
#    container_name: prometheus-bot
#    image: ilovecorea/prometheus-bot:latest
#    build:
#      context: prometheus_bot
#      dockerfile: Dockerfile
#    volumes:
#      - ./telegrambot/:/etc/telegrambot/
#      - ./telegrambot/config.yaml:/config.yaml
#    ports:
#      - 9087:9087
#    restart: always
#    networks:
#      - monitoring

#  alertmanager:
#    container_name: alertmanager
#    image: prom/alertmanager
#    ports:
#      - 9093:9093
#    volumes:
#      - ./alertmanager/:/etc/alertmanager/
#    restart: always
#    networks:
#      - monitoring
#    command:
#      - '--config.file=/etc/alertmanager/config.yml'
#      - '--storage.path=/alertmanager'
#    depends_on:
#      - prometheus-bot

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - consul-server
#      - alertmanager

  grafana:
    image: grafana/grafana:7.5.3
    container_name: grafana
    restart: always
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
    networks:
      - monitoring
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
