spring:
  application:
    name: hello
  profiles:
    active: #spring.profiles.active#
    group:
      consul:
        - logstash
  cloud:
    consul:
      enabled: false
  jackson:
    serialization:
      indent-output: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

logging:
  config:
    classpath:config/logback-spring.xml