global:
  scrape_interval: 15s

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: 'consul-server'
    metrics_path: '/v1/agent/metrics'
    params:
      format: [ 'prometheus' ]
    static_configs:
      - targets: [ 'consul-server:8500' ]

  - job_name: 'actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
#    static_configs:
#      - targets: [ 'host.docker.internal:8080' ]
    consul_sd_configs:
      - server: 'consul-server:8500'
    relabel_configs:
      - source_labels: [ __meta_consul_tags ]
        action: keep
      - source_labels: [ __meta_consul_service ]
        target_label: job

