logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.example.blog: INFO

spring:
  application:
    name: blog
  cloud:
    consul:
      enabled: false
  jackson:
    serialization:
      indent-output: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
