spring:
  application:
    name: blog
  profiles:
    active: #spring.profiles.active#
    group:
      consul:
        - logstash
  cloud:
    consul:
      enabled: false
  jackson:
    serialization:
      indent-output: true

server:
  port: 8080

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config:
    classpath:config/logback-spring.xml